[package]
name = "swim-core"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = [] }
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }