[workspace]
members = [
    "swim",
    "swim-core",
    "swim-util",
    "swim-contrib",
    "swim-db",
    "swim-cli",
    "swim-template",
    "swim-middleware",
]
exclude = [
    "examples/minimal",
    "examples/apps",
    "examples/middleware"
]