[package]
name = "base"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swim = { path = "../../../swim" }
async-trait = "0.1"